spring:
  application:
    name: order-management-service  datasource:
    url: jdbc:mysql://localhost:3306/somuca?useSSL=false
    #jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=ORDER;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    #org.h2.Driver
  jpa:
    hibernate:      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.dialect.storage_engine: innodb
      #org.hibernate.dialect.H2Dialect
  jackson:    serialization:      FAIL_ON_EMPTY_BEANS: false
  #h2:  #  console:  #   enabled: true
  #   path: /h2-console
# Management
management:  endpoints:
    web:      exposure:        include: "*"
  endpoint:
    health:
      show-details: ALWAYS      
server:  port: 9090  servlet:    context-path: /orderapi
