spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=ORDER;DB_CLOSE_ON_EXIT=FALSE
    #jdbc:mysql://localhost:3306/somuca?useSSL=false
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    #com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      #hibernate.dialect.storage_engine: innodb
      #org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
     enabled: true
     path: /h2-console
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: ramanaiah.237@gmail.com
    password: PASSWORD
    
# Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

camunda.bpm.admin-user:
  id: demo
  password: demo
  bpm:
    admin-user:
      filter: All tasks
camunda:
  bpm:
    client:
      worker-id: collateral
      base-url: http://localhost:8080/engine-rest
      max-tasks: 10
      lock-duration: 100000
      disable-auto-fetching: false

server:
  port: 9092
  servlet:
    context-path: /paymentapi
